activation: gelu
anormly_ratio: 0.5
batch_size: 64
d_ff: 32
d_model: 128
data_path: ./dataset/SAW2
dataset: SAW
dropout: 0.1
e_layers: 4
input_c: 1
isLabelled: true
lr: 0.001
mode: train
model_save_path: /content/drive/MyDrive/anomaly_runs/winsize_sweep
n_heads: 16
num_epochs: 10
output_c: 1
pretrained_model: null
seed: 42
win_size: 150
