activation: gelu
anormly_ratio: 0.5
batch_size: 32
d_ff: 512
d_model: 512
data_path: ./dataset/SAW2
dataset: SAW
dropout: 0.1
e_layers: 3
input_c: 1
isLabelled: true
lr: 1e-3
mode: test
model_save_path: checkpoints
n_heads: 8
num_epochs: 10
output_c: 1
pretrained_model: None
seed: 42
win_size: 200
